### ISSUE TITLE
gulp 4 vs 3 - TypeError: gulp.hasTask is not a function

### ISSUE THREAD

**Issue by olignyf** [mjhea0/express-testing-mocha-knex#2]
[15:09:07] TypeError: gulp.hasTask is not a function
    at /home/frank/express-testing-mocha-knex/node_modules/run-sequence/index.js:19:22
    at Array.forEach (native)
    at verifyTaskSets (/home/frank/express-testing-mocha-knex/node_modules/run-sequence/index.js:13:11)
    at /home/frank/express-testing-mocha-knex/node_modules/run-sequence/index.js:32:4

**Comment by olignyf** [comment]
Solution is to install the appropriate gulp and gulp-cli locally
`$ npm install gulp@3.9.1 gulp-cli@1.4.0`

**Comment by starkfire** [comment]
instead of downgrading to gulp 3.x, you might want to install `gulp4-run-sequence` instead
